# Generated by Django 4.0 on 2022-09-06 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('account', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 6, 13, 3, 34, 964582))),
            ],
        ),
    ]
