# Generated by Django 4.0 on 2022-09-06 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_account_alter_users_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='userimg',
            field=models.ImageField(null=True, upload_to='userimg/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 6, 13, 39, 43, 95667)),
        ),
    ]
