# Generated by Django 4.0 on 2022-09-06 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_gender_users_userimg_alter_users_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 6, 15, 32, 47, 770744), null=True),
        ),
    ]
