# Generated by Django 4.0 on 2022-09-10 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_users_account_post_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_activity',
            name='dateofpostactivity',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 10, 19, 19, 7, 434305)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 10, 19, 18, 52, 600958), null=True),
        ),
    ]
