# Generated by Django 4.0 on 2022-09-10 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_post_activity_dateofpostactivity_alter_users_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_activity',
            name='likes',
        ),
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 10, 20, 16, 48, 865880), null=True),
        ),
    ]
