# Generated by Django 4.0 on 2022-09-10 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_users_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_activity',
            new_name='post_activities',
        ),
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 10, 22, 14, 25, 411805), null=True),
        ),
    ]
